# Site settings
title: Rubber Duck Consulting
email: hello@rubberduckconsulting.co.uk
description: > # this means to ignore newlines until "baseurl:"
  Rubber Duck Consulting
baseurl: "" # the subpath of your site, e.g. /blog/
# url: "http://yourdomain.com" # the base hostname & protocol for your site
twitter_username: rdconsultingltd

# Build settings
markdown: kramdown


paginate: 3
paginate_path: "blog/page:num"
